[ja_nation]
JPN = "日本"
JPN_FML = "日本国"
USA = "アメリカ"
USA_FML = "アメリカ合衆国"
CHN = "中国"
CHN_FML = "中華人民共和国"
GBR = "イギリス"
GBR_FML = "グレートブリテン及び北アイルランド連合王国"
FRA = "フランス"
FRA_FML = "フランス共和国"
RUS = "ロシア"
RUS_FML = "ロシア連邦"
FRG = "西ドイツ"
FRG_FML = "ドイツ連邦共和国"
DDR = "東ドイツ"
DDR_FML = "ドイツ民主共和国"
ITA = "イタリア"
ITA_FML = "イタリア共和国"
AUS = "オーストリア"
AUS_FML = "オーストリア共和国"